name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  
  macos:

    runs-on: macos-latest

    name: macos

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
          restore-keys: |
            ${{ runner.os }}-QtCache
          

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install prerequisties
        run: |
         brew install muparser gsl gl2ps googletest
         pip install pyqt5 numpy sip PyQt-builder

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. -DORIGIN_IMPORT=ON -DSCRIPTING_PYTHON=ON -DPython3_ROOT_DIR=$pythonLocation \
            -DBUILD_TESTS=ON

      - name: Building
        run: |
          make -j$(sysctl -n hw.logicalcpu) -C build

      - name: Testing
        run: |
          cd build
          ctest --output-on-failure

      - name: Package with Architecture Info
        run: |
          ARCH=$(uname -m)
          mv build/outputfile build/outputfile-${ARCH}
